#!/bin/zsh
CURRENT_DIR=${0:a:h}
DOTFILES_ROOT=$(builtin cd $CURRENT_DIR/..; pwd)

source ${DOTFILES_ROOT}/path_defaults.zsh
# Import term colors
. $TERM_COLORS_PATH

# # Run all dotfiles installers.
# set -e

# cd "$(dirname "$0")"/..

# find the installers and run them iteratively
git ls-tree --name-only -r HEAD | grep install.sh | while read -r installer; do
	echo "${T_INFO}> ${installer}...${T_NORMAL}"
	sh -c "$installer"
done
